export default {
  'companies': [
    'Sailthru',
    'Grasshopper',
    'Outbrain',
    'CrowdTwist',
    'When I Work',
    'Ogilvy',
    'Odyssey',
    'charity: water',
    'GA Communication Group',
    'Bridgespan',
    'TYRA Beauty',
    'Gannett',
    'Birchbox',
    'Airbnb',
    'Lincoln Center',
    'Kiva',
    'Mashable',
    'NPR',
    'Sephora',
    'Heartland Alliance',
    'Goodwill',
    'Bluewolf',
    'HomeAway',
    'Warby Parker',
    'Pinterest',
    'GapTech',
    'Artsicle',
    'Levatas',
    'Uber',
    'TomTom',
    'StellaService',
    'Flickr',
    'OptionsCity',
    'StackCommerce',
    'Tasting Table',
    'Handy',
    'Yext',
    'Method',
    'Department of Labor',
    'Opower',
    'NFL',
    'ClaimTrak',
    'Twitch',
    'SXSW',
    'Continuum Analytics',
    'ScaleFactor',
    'Lithium',
    'SoFi',
    'ZestFinance',
    'Zoosk',
    'Dormify',
    'WeWork',
    'World Wildlife Fund',
    'Teach For America',
    'Dyn',
    'EF Education First',
    'Oprah Winfrey Network',
    'Sears Holdings',
    'Chicago Cubs',
    'Encyclopædia Britannica',
    'Fortegra',
    'Intelligentsia Coffee &amp; Tea',
    'Goose Island Brewery',
    'Bright Pink',
    'Pabst Brewing Company',
    'Pinsight Media+',
    'GEICO',
    'TED',
    'Zappos',
    'Venture For America',
    'Bookspan',
    'Nextdoor',
    'Freshbooks',
    '\'wichcraft',
    'AlphaSights',
    'Call Box (formerly Century Interactive)',
    'Bonobos',
    'CarMax',
    'CourseHorse',
    'Recombine',
    'Deloitte',
    'mywedding.com',
    'DogVacay',
    'Slack',
    'VMware',
    'Prezi',
    'Rubicon Project',
    'Black Mountain Systems',
    'Squarespace',
    'Contently',
    'Akilah Group',
    'GLG',
    'The Nerdery',
    'San Francisco Chronicle',
    'Screen Pilot',
    'Bitly',
    'Braintree',
    'Cortina Productions',
    'GrubHub',
    'Distractify',
    'Networked Insights',
    'Genesys',
    'Reebok',
    'Factual',
    'Codeup',
    'Dolby',
    'Bounce Exchange',
    'Upwork',
    'Cardlytics',
    'Spherical',
    'Symphony',
    'Tresta',
    'Radius',
    'Plated',
    'Axial',
    'Grafik',
    'Sir Kensington\'s',
    'Marriott International',
    'MM.LaFleur',
    'Rambler On',
    'RideScout',
    'Schoology',
    'Skout',
    'AddThis',
    'Taboola',
    'Balsam Brands',
    'Aviary',
    'The Muse',
    'TravelClick',
    'MailChimp',
    'Eventbrite',
    'AppNexus',
    'Hypertherm',
    'Omnigon',
    'Nestio',
    'VideoBlocks',
    'IEX Group',
    'mobileforming',
    'Placemeter',
    'Devmountain',
    'GoHealth',
    'SmartBear',
    'Medallia',
    'TripleLift',
    'Dow Jones',
    'Gravity',
    'Take-Two Interactive Software',
    'Hometeam',
    'Cloudera',
    'Spanx',
    'Hudl',
    'Citizen Schools',
    'eMarketer',
    'The Wall Street Journal',
    'Shutterstock',
    'Mohawk Industries',
    'Core Digital Media',
    'Good Apple Digital',
    'PivotDesk',
    'Brightbox',
    'ThoughtWorks',
    'Tile',
    'Funding Circle',
    'Dextro',
    'Stack Overflow',
    'DigitalOcean',
    'HBO',
    'One Month',
    'InMobi',
    'NextCapital',
    'GlobalGiving',
    'Bloomberg',
    'Cornerstone OnDemand',
    'MD Insider',
    'MediaRadar',
    'Payscape',
    'Fiverr',
    'Stylight',
    'Gigwalk',
    'RepEquity',
    'Rocket Games',
    'L2',
    'The New York Foundling',
    'HZDG',
    'Knot Standard',
    'Imagitas',
    'Pactiv',
    'Blinds.com',
    'Response Mine',
    'Engine Room Technology',
    'Ultimate Software',
    'Magoosh',
    'Progressive Insurance',
    'Corvirtus',
    'AOL',
    'Credit Karma',
    'Huge',
    'Spiceworks',
    'Rocksauce',
    'Horizon Group USA',
    'FTD Companies',
    'Goodwin Procter',
    'Yodle',
    'Treasure Data',
    'Ditto',
    'Insight Consulting Group',
    'Farmigo',
    'Owens &amp; Minor',
    'Alphaserve Technologies',
    'CEB',
    'Framebridge',
    'Ninthlink',
    'Karma',
    'KPMG',
    'Tilt',
    'Double Robotics',
    'Relias Learning',
    'Red Ventures',
    'iProspect',
    'HotelTonight',
    'Waypoint Homes',
    'Fetch Robotics',
    'Quantcast',
    'Outdoor Voices',
    'AbelsonTaylor',
    'PureWow',
    'Inspirato',
    'Clarabridge',
    'Rover',
    'CloudPassage',
    'Peanut Labs',
    'Oak Mortgage',
    'Penske Motor Group',
    'Jumpcut Studios',
    'OutboundEngine',
    'CARFAX',
    'King Arthur Flour',
    'TNTP',
    'LiveRamp',
    'HomeAdvisor',
    'Twilio',
    'Work Better',
    'Wellness Connection of Maine',
    'Euclid Analytics',
    'Fashion GPS',
    'Autodesk',
    'Spencer Stuart',
    'HealthcareSource',
    'JAMF Software',
    'Bai Brands',
    'Hillary for America',
    'Good Sports',
    'Dex Media',
    'Thoughtspot',
    'Bizzabo',
    'Moz',
    'Belly',
    'Ebates',
    'Circa Healthcare',
    'Smashbox Cosmetics',
    'Rain Bird',
    'Gap Inc.',
    'Veeva',
    'RevZilla',
    'Appian',
    'Imgur',
    'Persado',
    'App Annie',
    'CarGurus',
    'Cleveland Research Company',
    'Amazing.com',
    'M Financial Group',
    'TrackMaven',
    'Canvas',
    'YES Prep',
    'Trustwave',
    'The Broad Residency in Urban Education',
    'Ironhack',
    'Society for the Promotion of Japanese Animation',
    'BetterCloud',
    'NeueHouse',
    'City of Houston',
    'Lending Club',
    'W by Worth',
    'Guggenheim Partners',
    'MakerSquare',
    'HelloSign',
    'Vynamic',
    'Esri',
    'PulsePoint',
    '1871',
    'JINX',
    'Target',
    'SendGrid',
    'Swirl',
    'Anne Lewis Strategies',
    'Broadridge',
    'JDI',
    'Affect',
    'CA Technologies',
    'Counsyl',
    'Client Resources, Inc.',
    'Lytx',
    'Hearst Media Services',
    'Understory Weather',
    'BuildSavings',
    'Influenster',
    'Expedite Financial',
    'Work Market',
    'SmartBrief',
    'Banfield Pet Hospital',
    'Plum Organics',
    'Tapingo',
    'Grindr',
    'Ascendum',
    'Perfect Sense',
    'Conversant',
    'Redfin',
    'LegalZoom',
    'The Trium Group',
    'LivePerson',
    'Betterment',
    'Magnetic',
    'Education Pioneers',
    'iMedicare',
    'Shopify',
    'iCIMS',
    'Financial Finesse',
    'Redbubble',
    'TubeMogul',
    'Venmo',
    'Scribd',
    'Curacao',
    'Livefyre',
    'The Honest Company',
    'TripAdvisor',
    'Trumaker',
    'Entrepreneurs\' Organization',
    'Signpost',
    'Pep',
    'Andela',
    'Phase One',
    'Polaris',
    'Thumbtack',
    'Virool',
    'Gallup',
    'Main Street Hub',
    'Peloton Cycle',
    'OwnLocal',
    'DX Marketing',
    'the Washington Redskins',
    'OpenMarket',
    'Frontline Technologies',
    'Datadog',
    'Remix',
    'ProQuest',
    'Comcast',
    'DataSift',
    'Allstate',
    'LISI',
    'Armani',
    'Asana',
    'Skillshare',
    'Atlassian',
    'CommonBond',
    'ContextMedia',
    'LRN',
    'McKinsey',
    'Kasasa',
    'FiscalNote',
    'Elevation Church',
    'Nordson',
    'Yello',
    'Dia&amp;Co',
    'REVOLT',
    'Austin Film Festival',
    'Phoenix Energy',
    'Spredfast',
    'Pocket Gems',
    'POLITICO',
    'General Assembly',
    'Riviera',
    'Ziprealty',
    'Insikt',
    'Arrow Electronics',
    'Triose',
    'Jive',
    'Southern Management Corporation',
    '8020 Consulting',
    'VigLink',
    'DMC Atlanta',
    'AppFolio',
    'Return Path',
    'Goosehead Insurance',
    'Prosper Marketplace',
    'Bozzuto',
    'priceline.com',
    'The Avenue West',
    'Dun &amp; Bradstreet',
    'Lever',
    'Discovery',
    'Facebook',
    'Wallaby Financial',
    'Maven Wave',
    'Voxy',
    'W4',
    'Quintiles',
    'Dropbox',
    'Simplicity Consulting',
    'Daon',
    'Chartbeat',
    'City of Hope',
    'Fueled',
    'Condé Nast',
    'Owens Corning',
    'MuleSoft',
    'Duarte',
    'Galileo',
    'Roblox'
  ],
  'categories': [
    'Account Management',
    'Business &amp; Strategy',
    'Creative &amp; Design',
    'Customer Service',
    'Data Science',
    'Editorial',
    'Education',
    'Engineering',
    'Finance &amp; Data',
    'Fundraising &amp; Development',
    'Healthcare &amp; Medicine',
    'HR &amp; Recruiting',
    'Legal',
    'Marketing &amp; PR',
    'Operations',
    'Project &amp; Product Management',
    'Retail',
    'Sales',
    'Social Media &amp; Community'
  ],
  'levels': [
    'Internship',
    'Entry Level',
    'Mid Level',
    'Senior Level'
  ],
  'locations': [
    'Accra, GH',
    'Accra, Ghana',
    'A Coruna, Spain',
    'Albany, NY',
    'Albuquerque, NM',
    'Alexandria, LA',
    'Alexandria, VA',
    'Allentown, PA',
    'Almaty, Kazakhstan',
    'Amherst, MA',
    'Amsterdam, Netherlands',
    'Ankara, Turkey',
    'Ann Arbor, MI',
    'Asheville, NC',
    'Astana, Kazakhstan',
    'Athens, GR',
    'Athens, Greece',
    'Atlanta, GA',
    'Atlantic City, NJ',
    'Atyrau, Kazakhstan',
    'Auckland, New Zealand',
    'Auckland, NZ',
    'Augusta, GA',
    'Austin, TX',
    'Bakersfield, CA',
    'Baltimore, MD',
    'Bangalore, India',
    'Bangkok, Thailand',
    'Barcelona, Spain',
    'Basking Ridge, NJ',
    'Beaver Creek, CO',
    'Beaverton, MI',
    'Bedminster, NJ',
    'Beijing, China',
    'Bellingham, WA',
    'Bend, OR',
    'Berlin, Germany',
    'Billings, MT',
    'Biloxi, MS',
    'Birmingham, AL',
    'Birmingham, MI',
    'Bismarck, ND',
    'Bloomington, IL',
    'Bogota, Colombia',
    'Boise, ID',
    'Bologna, Italy',
    'Bonita Springs, FL',
    'Bordeaux, France',
    'Bossier City, LA',
    'Boston Metro Area',
    'Boulder, CO',
    'Bozeman, MT',
    'Branchburg, NJ',
    'Brewer, ME',
    'Bridgeport, CT',
    'Brighton, UK',
    'Brisbane, Australia',
    'Bristol, TN',
    'Bristol, UK',
    'Brussels, Belgium',
    'Bucharest, Romania',
    'Budapest, HU',
    'Budapest, Hungary',
    'Buenos Aires, Argentina',
    'Buffalo, NY',
    'Burlington, MA',
    'Burlington, VT',
    'Bursa, Turkey',
    'Busan, South Korea',
    'Calhoun, GA',
    'Canberra, Australia',
    'Center Valley, PA',
    'Chandigarh, India',
    'Charleston, SC',
    'Charleston, WV',
    'Charlotte, NC',
    'Charlottesville, VA',
    'Chengdu, China',
    'Chennai, India',
    'Chevy Chase, MD',
    'Chicago, IL',
    'Chongqing, China',
    'Cincinnati, OH',
    'Cleveland, OH',
    'Coffeyville, KS',
    'College Station, TX',
    'Colorado Springs, CO',
    'Columbia, MO',
    'Columbia, SC',
    'Columbus, GA',
    'Columbus, OH',
    'Copenhagen, Denmark',
    'Cork, Ireland',
    'Corpus Christi, TX',
    'Dallas/Ft. Worth, TX',
    'Dalton, GA',
    'Daytona Beach, FL',
    'Denver, CO',
    'Des Moines, IA',
    'Detroit, MI',
    'Dodge City, KS',
    'Dreieich, Germany',
    'Dubai, UAE',
    'Dublin, IE',
    'Dublin, Ireland',
    'Duluth, MN',
    'Durham, NC',
    'Dusseldorf, Germany',
    'East Stroudsburg, PA',
    'Eau Claire, WI',
    'El Paso, TX',
    'Eugene, OR',
    'Fayetteville, AR',
    'Flexible / Remote',
    'Florence, Italy',
    'Fort Collins, CO',
    'Fort Wayne, IN',
    'Fort Worth, TX',
    'Frankfurt, Germany',
    'Fresno, CA',
    'Ft. Myers, FL',
    'Fukuoka, Japan',
    'Galway, Ireland',
    'Glasgow, SCT',
    'Golden, CO',
    'Grand Rapids, MI',
    'Greenville, SC',
    'Guangzhou, China',
    'Guragon, India',
    'Hamburg, Germany',
    'Hamilton, Bermuda',
    'Hamilton, NJ',
    'Hangzhou, China',
    'Hanoi, Vietnam',
    'Hanover, NH',
    'Harker Heights, TX',
    'Harrisburg, PA',
    'Hartford, CT',
    'Helena, MT',
    'Helsinki, Finland',
    'Hermosillo, Mexico',
    'Hingham, MA',
    'Ho Chi Minh City, Vietnam',
    'Hong Kong',
    'Honolulu, HI',
    'Houston, TX',
    'Huntsville, AL',
    'Hunt Valley, MD',
    'Hyderabad, India',
    'Indianapolis, IN',
    'International',
    'Istanbul, Turkey',
    'Jackson, MS',
    'Jacksonville, FL',
    'Jakarta, Indonesia',
    'Johannesburg, South Africa',
    'Johnstown, PA',
    'Joplin, MO',
    'Kampala, UG',
    'Kansas City, KS',
    'Kansas City, MO',
    'Kazan, Russia',
    'Kiev, Ukraine',
    'Kitchener, Canada',
    'Knoxville, TN',
    'Kyoto, Japan',
    'Lafayette, LA',
    'Lagos, Nigeria',
    'Lancaster, PA',
    'Landover, MD',
    'Las Vegas, NV',
    'Lausanne, CH',
    'Lebanon, NH',
    'Lexington, KY',
    'Lille, France',
    'Lilongwe, MW',
    'Lima, OH',
    'Lima, Peru',
    'Lincoln, NE',
    'Little Rock, AR',
    'London, UK',
    'Long Island, NY',
    'Los Angeles, CA',
    'Louisville, KY',
    'Luxembourg City, Luxembourg',
    'Lyon, France',
    'Macau, China',
    'Macon, GA',
    'Madison, WI',
    'Madrid, ES',
    'Madrid, Spain',
    'Malaga, Spain',
    'Manchester, NH',
    'Manhattan, NY',
    'Manila, Philippines',
    'Marseille, France',
    'McAllen, TX',
    'Medford, OR',
    'Melbourne, AU',
    'Melbourne, Australia',
    'Memphis,TN',
    'Mendoza, Argentina',
    'Mexico City, Mexico',
    'Miami, FL',
    'Milan, Italy',
    'Milton, DE',
    'Milwaukee, WI',
    'Minneapolis, MN',
    'Mobile, AL',
    'Monterrey, Mexico',
    'Montgomery, AL',
    'Montreal, Canada',
    'Moscow, Russia',
    'Mountain Home, AR',
    'Mountain Side, NJ',
    'Mt. Vernon, WA',
    'Multiple',
    'Mumbai, India',
    'Munich, DE',
    'Munich, Germany',
    'Myrtle Beach, SC',
    'Nagoya, Japan',
    'Nairobi, Kenya',
    'Nanjing, China',
    'Naples, Italy',
    'Nashua, NH',
    'Nashville, TN',
    'Netanya, Israel',
    'Newark, DE',
    'New Berlin, WI',
    'Newcastle, Australia',
    'New Delhi, India',
    'New Haven, CT',
    'New Orleans, LA',
    'New York City Metro Area',
    'Nogales, Mexico',
    'Norwalk, CT',
    'Norwich, VT',
    'Novosibirsk, Russia',
    'Odessa, Ukraine',
    'Oklahoma City, OK',
    'Olympia, WA',
    'Omaha, NE',
    'Orange County, CA',
    'Orlando, FL',
    'Osaka, Japan',
    'Oslo, Norway',
    'Ostrava, Czech Republic',
    'Ottawa, Canada',
    'Oxford, UK',
    'Oxnard, CA',
    'Padua, Italy',
    'Palm Bay, FL',
    'Palm Beach, FL',
    'Palm Springs, CA',
    'Panama City, FL',
    'Paris, FR',
    'Paris, France',
    'Parkersburg, WV',
    'Pasadena, CA',
    'Pensacola, FL',
    'Peoria, IL',
    'Perth, Australia',
    'Philadelphia, PA',
    'Phoenix, AZ',
    'Piscataway, NJ',
    'Pittsburgh, PA',
    'Plano, TX',
    'Plattsburgh, NY',
    'Portland, ME',
    'Portland, OR',
    'Porto Alegre, Brazil',
    'Prague, Czech Republic',
    'Princeton, NJ',
    'Providence, RI',
    'Provo, UT',
    'Queens, NY',
    'Quito, Ecuador',
    'Ra\'anana, Israel',
    'Raleigh, NC',
    'Reading, UK',
    'Regina, Canada',
    'Reno, NV',
    'Richmond, VA',
    'Riga, Latvia',
    'Rio de Janeiro, Brazil',
    'Roanoke, VA',
    'Rochester, NY',
    'Rome, Italy',
    'Sacramento Metro Area',
    'Saint John, Canada',
    'Saint Louis, MO',
    'Salt Lake City, UT',
    'San Antonio Metro Area',
    'San Diego, CA',
    'San Francisco Bay Area',
    'San Jose, CA',
    'Santa Barbara, CA',
    'Santa Cruz, CA',
    'Santiago, Chile',
    'Sao Paolo, BR',
    'Sao Paolo, Brazil',
    'Sapporo, Japan',
    'Savannah, GA',
    'Scottsdale, AZ',
    'Seattle, WA',
    'Secaucus, NJ',
    'Seoul, Korea',
    'Seville, ES',
    'Shanghai, China',
    'Shenzhen, China',
    'Short Hills, NJ',
    'Shreveport, LA',
    'Silicon Valley, CA',
    'Singapore',
    'Spokane, WA',
    'Springfield, IL',
    'Stockholm, Sweden',
    'St. Petersburg, Russia',
    'Sugar Valley, GA',
    'Surabaya, Indonesia',
    'Sydney, AU',
    'Sydney, Australia',
    'Syracuse, NY',
    'Tahoe City, CA',
    'Taipei, Taiwan',
    'Taizhou, China',
    'Tallahassee, FL',
    'Tallinn, Estonia',
    'Tampa, FL',
    'Tel Aviv, Israel',
    'Tijuana, Mexico',
    'Tokyo, Japan',
    'Toledo, OH',
    'Topeka, KS',
    'Toronto, CA',
    'Toronto, Canada',
    'Traverse City, MI',
    'Tucson, AZ',
    'Tulsa, OK',
    'Valencia, Spain',
    'Valletta, Malta',
    'Vancouver, Canada',
    'Venice, Italy',
    'Vienna, Austria',
    'Villahermosa, Mexico',
    'Virginia Beach, VA',
    'Warsaw, Poland',
    'Washington DC Metro Area',
    'Waterloo, Canada',
    'Wellington, NZ',
    'Westlake Village, CA',
    'Westport, CT',
    'Wilmington, DE',
    'Winnipeg, Canada',
    'Wuhan, China',
    'Wuxi, China',
    'Wyomissing, PA',
    'Xi\'an, China',
    'Zurich, Switzerland'
  ]
};
